USE [master]
GO
/****** Object:  Database [Kamenetskiyy_DB_02]    Script Date: 16.12.2025 11:44:01 ******/
CREATE DATABASE [Kamenetskiyy_DB_02]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Kamenetskiyy_DB_02', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Kamenetskiyy_DB_02.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Kamenetskiyy_DB_02_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Kamenetskiyy_DB_02_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Kamenetskiyy_DB_02].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET ARITHABORT OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET RECOVERY FULL 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET  MULTI_USER 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Kamenetskiyy_DB_02', N'ON'
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET QUERY_STORE = ON
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Kamenetskiyy_DB_02]
GO
/****** Object:  Table [dbo].[Ad]    Script Date: 16.12.2025 11:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ad](
	[AdId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[PublishDate] [date] NOT NULL,
	[CompleteDate] [date] NULL,
	[CityId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[CategoryId] [int] NOT NULL,
	[AdTypeId] [int] NOT NULL,
	[AdStatusId] [int] NOT NULL,
 CONSTRAINT [PK_Ad] PRIMARY KEY CLUSTERED 
(
	[AdId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AdsRaw]    Script Date: 16.12.2025 11:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdsRaw](
	[user_login] [nvarchar](50) NULL,
	[user_password] [nvarchar](50) NULL,
	[ad_title] [nvarchar](200) NULL,
	[ad_description] [nvarchar](max) NULL,
	[ad_post_date] [date] NULL,
	[city] [nvarchar](100) NULL,
	[category] [nvarchar](100) NULL,
	[ad_type] [nvarchar](50) NULL,
	[ad_status] [nvarchar](50) NULL,
	[price] [decimal](18, 2) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AdStatus]    Script Date: 16.12.2025 11:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdStatus](
	[AdStatusId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_AdStatus] PRIMARY KEY CLUSTERED 
(
	[AdStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_AdStatus_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AdType]    Script Date: 16.12.2025 11:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdType](
	[AdTypeId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_AdType] PRIMARY KEY CLUSTERED 
(
	[AdTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_AdType_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 16.12.2025 11:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Category_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[City]    Script Date: 16.12.2025 11:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[City](
	[CityId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[CityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_City_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 16.12.2025 11:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Login] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[FullName] [nvarchar](200) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_User_Login] UNIQUE NONCLUSTERED 
(
	[Login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ad_Category]    Script Date: 16.12.2025 11:44:02 ******/
CREATE NONCLUSTERED INDEX [IX_Ad_Category] ON [dbo].[Ad]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ad_City]    Script Date: 16.12.2025 11:44:02 ******/
CREATE NONCLUSTERED INDEX [IX_Ad_City] ON [dbo].[Ad]
(
	[CityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ad_Status]    Script Date: 16.12.2025 11:44:02 ******/
CREATE NONCLUSTERED INDEX [IX_Ad_Status] ON [dbo].[Ad]
(
	[AdStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Ad_Title]    Script Date: 16.12.2025 11:44:02 ******/
CREATE NONCLUSTERED INDEX [IX_Ad_Title] ON [dbo].[Ad]
(
	[Title] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ad_Type]    Script Date: 16.12.2025 11:44:02 ******/
CREATE NONCLUSTERED INDEX [IX_Ad_Type] ON [dbo].[Ad]
(
	[AdTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ad_User]    Script Date: 16.12.2025 11:44:02 ******/
CREATE NONCLUSTERED INDEX [IX_Ad_User] ON [dbo].[Ad]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ad]  WITH CHECK ADD  CONSTRAINT [FK_Ad_AdStatus] FOREIGN KEY([AdStatusId])
REFERENCES [dbo].[AdStatus] ([AdStatusId])
GO
ALTER TABLE [dbo].[Ad] CHECK CONSTRAINT [FK_Ad_AdStatus]
GO
ALTER TABLE [dbo].[Ad]  WITH CHECK ADD  CONSTRAINT [FK_Ad_AdType] FOREIGN KEY([AdTypeId])
REFERENCES [dbo].[AdType] ([AdTypeId])
GO
ALTER TABLE [dbo].[Ad] CHECK CONSTRAINT [FK_Ad_AdType]
GO
ALTER TABLE [dbo].[Ad]  WITH CHECK ADD  CONSTRAINT [FK_Ad_Category] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([CategoryId])
GO
ALTER TABLE [dbo].[Ad] CHECK CONSTRAINT [FK_Ad_Category]
GO
ALTER TABLE [dbo].[Ad]  WITH CHECK ADD  CONSTRAINT [FK_Ad_City] FOREIGN KEY([CityId])
REFERENCES [dbo].[City] ([CityId])
GO
ALTER TABLE [dbo].[Ad] CHECK CONSTRAINT [FK_Ad_City]
GO
ALTER TABLE [dbo].[Ad]  WITH CHECK ADD  CONSTRAINT [FK_Ad_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserId])
GO
ALTER TABLE [dbo].[Ad] CHECK CONSTRAINT [FK_Ad_User]
GO
USE [master]
GO
ALTER DATABASE [Kamenetskiyy_DB_02] SET  READ_WRITE 
GO
