//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int AdId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PublishDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public int CityId { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public int AdTypeId { get; set; }
        public int AdStatusId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual AdStatus AdStatus { get; set; }
        public virtual AdType AdType { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
